SELECT C.FIRST_NAME, C.LAST_NAME, R.RENTAL_DATE FROM CUSTOMER C INNER JOIN RENTAL R ON C.CUSTOMERID=R.RENTALID ORDER BY R.RENTAL_DATE DESC LIMIT 1;

SELECT C.FIRST_NAME, C.LAST_NAME, L.RENTAL_DATE FROM (SELECT CUSTOMERID, MAX(RENTAL_DATE) AS RENTAL_DATE FROM RENTAL) AS LONGRENTAL L INNER JOIN CUSTOMER C ON C.CUSTOMERID=R.RENTALID;